<select onchange="return help_me_ideas(this)">
    <optgroup label="MORE ABOUT ME">
        <option value="0"> <a href="">&nbsp;&nbsp;&nbsp;</option>
        <option value="What is my middle name?">What is my middle name?</option>
        <option value="What is my dog's name?">What is my dog's name?</option>
        <option value="How many stuffed animals do I have in my room?">How many stuffed animals do I have in my room?</option>
        <option value="What is my biggest pet peeve?">What is my biggest pet peeve?</option>
        <option value="What is my biggest fear?">What is my biggest fear?</option>
        <option value="Do I like rollercoasters?">Do I like rollercoasters?</option>
        <option value="What is my most prized possesion?">What is my most prized possesion?</option>
        <option value="What is the name of my first pet?">What is the name of my first pet?</option>
        <option value="Who is my celebrity crush?">Who is my celebrity crush?</option>
        <option value="What is my cat's name?">What is my cat's name?</option>
        <option value="Do I exercise?">Do I exercise?</option>
        <option value="When is the last time I cried?">When is the last time I cried?</option>
        <option value="What is my hair color?">What is my hair color?</option>
        <option value="How tall am I?">How tall am I?</option>
        <option value="How many states have I visited?">How many states have I visited?</option>
        <option value="How many countries have I visited?">How many countries have I visited?</option>
        <option value="How many broken bones have I had?">How many broken bones have I had?</option>
        <option value="What is my birthday?">What is my birthday?</option>
        <option value="How old am I?">How old am I?</option>
        <option value="How many siblings do I have?">How many siblings do I have?</option>
        <option value="How many pets do I have?">How many pets do I have?</option>
        <option value="Do I like to dance?">Do I like to dance?</option>
        <option value="What is my nickname?">What is my nickname?</option>
        <option value="Am I left or right handed?">Am I left or right handed?</option>
        <option value="Am I a morning person? ">Am I a morning person? </option>
        <option value="What is my eye color?">What is my eye color?</option>
        <option value="Do I have my own room?">Do I have my own room?</option>
        <option value="Do I like Frozen?">Do I like Frozen?</option>
        <option value="Do I like sports?">Do I like sports?</option>
        <option value="Do I like to read?">Do I like to read?</option>
        <option value="Do I like to swim?">Do I like to swim?</option>
        <option value="Do I like to draw?">Do I like to draw?</option>
        <option value="How many posters are hanging in my room?">How many posters are hanging in my room?</option>
        <option value="If I could have a superpower, what would it be?">If I could have a superpower, what would it be?</option>
        <option value="Are my ears pierced? ">Are my ears pierced? </option>
        <option value="How many pairs of shoes do I own?">How many pairs of shoes do I own?</option>
        <option value="Who is my best friend?">Who is my best friend?</option>
        <option value="Am I a Swiftie (Taylor Swift fan)?">Am I a Swiftie (Taylor Swift fan)?</option>
        <option value="Have I ever colored my hair?">Have I ever colored my hair?</option>
        <option value="Do I like school?">Do I like school?</option>
        <option value="What annoys me the most?">What annoys me the most?</option>
        <option value="What app do I use the most ?">What app do I use the most ?</option>
        <option value="What color is my room?">What color is my room?</option>
        <option value="What do I like doing to try to fall asleep? ">What do I like doing to try to fall asleep? </option>
        <option value="What do I have for breakfast every morning? ">What do I have for breakfast every morning? </option>
        <option value="What is my nickname?">What is my nickname?</option>
        <option value="What do I want to be when I grow up?">What do I want to be when I grow up?</option>
        <option value="What stuffed animal do I sleep with?">What stuffed animal do I sleep with?</option>
    </optgroup>
    <optgroup label="FAVORITES">
        <option value="Who is my favorite author?">Who is my favorite author?</option>
        <option value="Who is my favorite singer?">Who is my favorite singer?</option>
        <option value="What is my favorite song?">What is my favorite song?</option>
        <option value="What is my favorite movie?">What is my favorite movie?</option>
        <option value="What is my favorite color?">What is my favorite color?</option>
        <option value="What is my favorite sport?">What is my favorite sport?</option>
        <option value="What is my favorite food?">What is my favorite food?</option>
        <option value="What is my favorite animal?">What is my favorite animal?</option>
        <option value="What is my favorite team?">What is my favorite team?</option>
        <option value="What is my favorite number?">What is my favorite number?</option>
        <option value="What is my favorite subject in school?">What is my favorite subject in school?</option>
        <option value="What is my favorite band?">What is my favorite band?</option>
        <option value="What is my favorite restaurant?">What is my favorite restaurant?</option>
        <option value="What is my favorite game?">What is my favorite game?</option>
        <option value="What is my favorite drink?">What is my favorite drink?</option>
        <option value="What is my favorite time of day?">What is my favorite time of day?</option>
        <option value="What is my favorite candy?">What is my favorite candy?</option>
        <option value="What is my favorite season?">What is my favorite season?</option>
        <option value="What is my favorite saying?">What is my favorite saying?</option>
        <option value="What is my favorite book?">What is my favorite book?</option>
        <option value="What is my favorite holiday?">What is my favorite holiday?</option>
        <option value="What is my favorite hobby?">What is my favorite hobby?</option>
        <option value="What is my favorite ice cream flavor?">What is my favorite ice cream flavor?</option>
        <option value="What is my favorite thing to do?">What is my favorite thing to do?</option>
        <option value="What is my favorite fruit?">What is my favorite fruit?</option>
        <option value="Where is my favorite place to vacation?">Where is my favorite place to vacation?</option>
        <option value="What in my favorite thing to do in my spare time?">What in my favorite thing to do in my spare time?</option>
        <option value="What is my favorite TV show?">What is my favorite TV show?</option>
        <option value="Who is my favorite actor?">Who is my favorite actor?</option>
        <option value="Who is my favorite actress?">Who is my favorite actress?</option>
        <option value="What is my favorite Disney movie?">What is my favorite Disney movie?</option>
        <option value="Who is my favorite Disney princess?">Who is my favorite Disney princess?</option>
        <option value="Who is my favorite super hero?">Who is my favorite super hero?</option>
        <option value="What is my favorite class?">What is my favorite class?</option>
        <option value="Who is my favorite teacher?">Who is my favorite teacher?</option>
        <option value="What is my favorite clothing brand?">What is my favorite clothing brand?</option>
        <option value="What is my favorite brand of shoes?">What is my favorite brand of shoes?</option>
        <option value="What is my favorite store to shop at?">What is my favorite store to shop at?</option>
        <option value="What are my favorite flavor of chips? ">What are my favorite flavor of chips? </option>
        <option value="What is my favorite amusement park?">What is my favorite amusement park?</option>
        <option value="What is my favorite memory?">What is my favorite memory?</option>
        <option value="What is my favorite cartoon?">What is my favorite cartoon?</option>
        <option value="What is my second most favorite color?">What is my second most favorite color?</option>
        <option value="What is my favorite board game?">What is my favorite board game?</option>
        <option value="What is my favorite instrument?">What is my favorite instrument?</option>
        <option value="Who is my favorite player?">Who is my favorite player?</option>
        <option value="Who is my favorite celebrity?">Who is my favorite celebrity?</option>
    </optgroup>
    <optgroup label="LEAST FAVORITES">
        <option value="Who is my least favorite singer?">Who is my least favorite singer?</option>
        <option value="What is my least favorite song?">What is my least favorite song?</option>
        <option value="What is my least favorite movie?">What is my least favorite movie?</option>
        <option value="What is my least favorite TV show?">What is my least favorite TV show?</option>
        <option value="What is my least favorite color?">What is my least favorite color?</option>
        <option value="What is my least favorite sport?">What is my least favorite sport?</option>
        <option value="What is my least favorite food?">What is my least favorite food?</option>
        <option value="What is my least favorite team?">What is my least favorite team?</option>
        <option value="What is my least favorite subject in school?">What is my least favorite subject in school?</option>
        <option value="What is my least favorite band?">What is my least favorite band?</option>
        <option value="What is my least favorite restaurant?">What is my least favorite restaurant?</option>
        <option value="What is my least favorite season?">What is my least favorite season?</option>
        <option value="Who is my least favorite player?">Who is my least favorite player?</option>
        <option value="Who is my least favorite celebrity?">Who is my least favorite celebrity?</option>
        <option value="What is my least favorite ice cream flavor?">What is my least favorite ice cream flavor?</option>
        <option value="What is my least favorite thing to do?">What is my least favorite thing to do?</option>
        <option value="What is my least favorite fruit?">What is my least favorite fruit?</option>
        <option value="Where is my least favorite place to vacation?">Where is my least favorite place to vacation?</option>
        <option value="Who is my least favorite actor?">Who is my least favorite actor?</option>
        <option value="Who is my least favorite actress?">Who is my least favorite actress?</option>
        <option value="What is my least favorite Disney movie?">What is my least favorite Disney movie?</option>
        <option value="Who is my least favorite Disney princess?">Who is my least favorite Disney princess?</option>
        <option value="What is my least favorite store to shop at?">What is my least favorite store to shop at?</option>
        <option value="What is my least favorite class?">What is my least favorite class?</option>
    </optgroup>
    <optgroup label="JUST FOR FUN">
        <option value="The weirdest food that I've ever eaten is:">The weirdest food that I've ever eaten is:</option>
        <option value="Am I sassy?">Am I sassy?</option>
        <option value="Do I wear long or short socks usually?">Do I wear long or short socks usually?</option>
        <option value="Which did I not get for Christmas last year?">Which did I not get for Christmas last year?</option>
        <option value="Which of the following have I never eaten?">Which of the following have I never eaten?</option>
        <option value="How much wood could a wood-chuck chuck?">How much wood could a wood-chuck chuck?</option>
        <option value="The strangest place that I've ever been is:">The strangest place that I've ever been is:</option>
        <option value="What is my favorite gum?">What is my favorite gum?</option>
        <option value="Do I have sick dance moves?">Do I have sick dance moves?</option>
        <option value="Am I wearing socks right now?">Am I wearing socks right now?</option>
        <option value="Am I awesome ?">Am I awesome ?</option>
        <option value="Why did the chicken cross the road?">Why did the chicken cross the road?</option>
        <option value="What is my favorite cheese?">What is my favorite cheese?</option>
        <option value="What color is my favorite hat?">What color is my favorite hat?</option>
        <option value="If I were a farm animal, I would be:">If I were a farm animal, I would be:</option>
        <option value="If Disney made a movie of my life, it would be called:">If Disney made a movie of my life, it would be called:</option>
        <option value="Which of the following really gives me the creeps?">Which of the following really gives me the creeps?</option>
        <option value="If I were a candy bar, I would be a:">If I were a candy bar, I would be a:</option>
        <option value="If I were a fruit smoothie, I would be:">If I were a fruit smoothie, I would be:</option>
        <option value="If I were a cereal, I would be:">If I were a cereal, I would be:</option>
        <option value="Mustard, Ketchup, Mayo or Ranch Dressing?">Mustard, Ketchup, Mayo or Ranch Dressing?</option>
    </optgroup>
</select>